"use std::path::Path;\nuse std::io::{self, Read, Seek, SeekFrom};\nuse unpak::Pak;\nuse tauri::AppHandle;\nuse crate::commands::keys::{get_all_keys, hex_to_key_bytes};\nuse crate::commands::wwiser::emit_log;\n\n/// The UE4 pak magic number\nconst PAK_MAGIC: u32 = 0x5A6F12E1;\n\n/// Read the encryption key GUID from a pak file's footer.\n/// Returns (version_u32, encryption_guid_hex, is_encrypted)\nfn read_pak_footer_info(path: &Path) -> Result<(u32, String, bool), String> {\n    let mut file = std::fs::File::open(path).map_err(|e| format!(\"Cannot open {}: {}\", path.display(), e))?;\n    let file_size = file.metadata().map_err(|e| e.to_string())?.len();\n    \n    // UE4 pak footer is at the end. We need to try different version footer sizes.\n    // Version 11 (Fnv64BugFix / latest) has the largest footer.\n    // Footer layout (read from end, backwards):\n    //   - compression_names: 5 * 32 bytes = 160 (v8+)\n    //   - hash: 20 bytes\n    //   - index_size: 8 bytes  \n    //   - index_offset: 8 bytes\n    //   - version: 4 bytes\n    //   - magic: 4 bytes\n    //   - encrypted: 1 byte (v4+)\n    //   - encryption_key_uuid: 16 bytes (v7+)\n    // Total for v11: 16 + 1 + 4 + 4 + 8 + 8 + 20 + 160 = 221 bytes\n    \n    // Try versions from newest to oldest\n    let version_configs: Vec<(u32, i64)> = vec![\n        // (expected_version, footer_size)\n        (11, 221), // Fnv64BugFix  \n        (10, 221), // PathHashIndex\n        (9, 222),  // FrozenIndex (has extra frozen byte)\n        (8, 221),  // FNameBasedCompression2 (5 compression names)\n        (8, 189),  // FNameBasedCompression (4 compression names)\n        (7, 61),   // EncryptionKeyUuid (no compression names)\n        (6, 44),   // DeleteRecords\n        (5, 44),   // RelativeChunkOffsets  \n        (4, 45),   // IndexEncryption\n        (3, 44),   // CompressionEncryption\n    ];\n\n    for (expected_ver, footer_size) in &version_configs {\n        if (file_size as i64) < *footer_size {\n            continue;\n        }\n        \n        file.s
<truncated 21934 bytes>
// REPLACED:
"                            if guid_hex.len() == 32 {\n                                let a = guid_hex[6..8].to_string() + &guid_hex[4..6] + &guid_hex[2..4] + &guid_hex[0..2];\n                                let b = guid_hex[10..12].to_string() + &guid_hex[8..10];\n                                let c = guid_hex[14..16].to_string() + &guid_hex[12..14];\n                                let d = &guid_hex[16..32];"
// REPLACED:
"    let version_configs: Vec<(u32, i64)> = vec![\n        // (expected_version, footer_size)\n        (12, 221), // WutheringWaves\n        (11, 221), // Fnv64BugFix  "
// REPLACED:
"#[tauri::command]\npub fn test_pak_mount(app: AppHandle, state: tauri::State<'_, crate::config::ConfigState>) -> Result<String, String> {"
// REPLACED:
"            } else if path.extension().and_then(|e| e.to_str()).map(|s| s.to_lowercase()) == Some(\"pak\".to_string()) {"